### ISSUE TITLE
Support managing security groups

### ISSUE THREAD

**Issue by geofffranks** [jhunt/cf-plugin-deploy#6]
Allow cf-plugin-deploy to create security/update groups in CF, and assign them to global defaults for staging/running apps, or to individual orgs/spaces

```
security_groups:
- name: org-sg
   rules:
   - destination: 10.0.0.1
      protocol: all
- name: space-sg
   rules:
   - destination: 10.0.0.2
      protocol: all
- name: global-sg
   rules:
   - destination: 10.0.0.3
     protocol: all
global_security_groups:
  staging:
  - global-sg
  running:
  - global-sg
organizations:
  my-org:
     security-groups:
     - org-sg
     spaces:
     - space-sg
````

Rules contents should just be jsonified, not necessarily inspected for anything, and pushed as SG contents.

**Comment by norman-abramovitz** [comment]
Changing security groups to look more like this since it is the security group name that needs to be looked up.   Also, a security group file contains an array of security group items and the whole array is given a name.   There is no syntax for inline JSON on the command line.

```yaml
security_groups:
  org-sg:
    rules:
    - destination: 10.0.0.1
      protocol: all
      log: true
  space-sg:
    rules:
    - destination: 10.0.0.2
      protocol: all
    - destination: 10.0.0.2
      protocol: icmp
      code: -1
  global-sg:
    rules:
    - destination: 10.0.0.3
      protocol: all
```

> The provided path can be an absolute or relative path to a file.  The file should have a single array of JSON objects inside describing the rules.  The JSON Base Object is omitted and only the square brackets and associated child object are required in the file.

**Comment by geofffranks** [comment]
if you drop the `name:` key from each group, relying on the key for that, maybe also drop the `rules:` key, for something like:

```
security_groups:
  org-sg:
  - destination: 10.0.0.1
     protocol: all
     log: true
```
